version: '3'
services:
  demo-app:
    image: ighojohn/demo-app:${IMAGE_TAG}
    container_name: demo-app
    ports:
      - "8080:8080"
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=my_pwd
    ports:
      - "5432:5432"

