#!/usr/bin/env groovy
@Library('jenkins-shared-library')
def gv

pipeline {
    agent any
    stages {
        stage("build jar") {
            steps {
                buildJar()
            }
        }
        stage("build image") {
            steps {
                buildImage()
            }
        }
        stage("deploy") {
            steps {
                echo "deploy stage placeholder"
            }
        }
    }
}
