#!/usr/bin/env groovy
@Library('jenkins-shared-library')
def gv

pipeline {
    agent any
    tools {
        maven 'maven-3.9.16'
    }
    stages {
        stage("build jar") {
            steps {
                buildJar 'ighojohn/demo-app:jma-2.0'
            }
        }
        stage("build image") {
            steps {
                buildImage()
            }
        }
        stage("deploy") {
            steps {
                echo "deploy stage placeholder"
            }
        }
    }
}
