#!/usr/bin/env groovy
@Library('jenkins-shared-library') _

pipeline {
    agent any
    tools {
        maven 'maven-3.9.16'
    }
    environment {
        IMAGE_NAME = "ighojohn/testing-app:23"
        CONTAINER_NAME = "testing-app"
    }
    stages {
        stage("build jar") {
            steps {
                buildJar()
            }
        }
        stage("build image") {
            steps {
                buildImage("${IMAGE_NAME}")
            }
        }
        stage("docker login") {
            steps {
                dockerlogin()
            }
        }
        stage("docker push") {
            steps {
                dockerPush("${IMAGE_NAME}")
            }
        }
        stage("deploy") {
            steps {
                script {
                    def dockerCmd = "docker stop ${CONTAINER_NAME} || true && docker rm ${CONTAINER_NAME} || true && docker run -p 3000:80 -d --name ${CONTAINER_NAME} ${IMAGE_NAME}"
                    sshagent(['ec2-server-key']) {
                        sh "ssh -o StrictHostKeyChecking=no ec2-user@99.79.70.217 '${dockerCmd}'"
                    }
                }
            }
        }
    }
}
